### ISSUE TITLE
Image Upload for Mobile Browsers

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#1]
When I try to upload images from a mobile browser, the only way to do so is through the camera. Can you please make sure all android devices allow the user to select a picture from the Gallery? Similarly, iOS users should be able to pick photos from the device in addition to the camera.

![Uploading image.png…]()

**Comment by cyrus-gc** [comment]
We have checked this using the mobiles we have here. We see two options, first one is the camera and the second is from the Gallery. Please send us the screenshot where you faced this issue.

**Comment by mailanand75** [comment]
Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/12179089/9607138/1ff1b94a-50e5-11e5-8c4d-55cacaf4f5b9.png)

**Comment by cyrus-gc** [comment]
This is the default expected behavior of the Android File Dialog window. The user can select the Documents which will have Gallery, images, folders that has images in it.

**Comment by mailanand75** [comment]
Alrite I am closing this.
