### ISSUE TITLE
Typo in the email sent for confirmation access to guides

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#103]
In the below email, please remove the full stop after the exclamation mark after "....delete it!" This is applicable for both men's and women's guide.

---

Hi Raj,

Please click here to access The Men's Guide to creating a Biodata for Marriage.

If you received this email by mistake, simply delete it!. You won't be subscribed if you don't click the confirmation link above.

Regards,
Jodi Logik Minions
Create Cool, Custom Biodata for Marriage

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.

**Comment by mailanand75** [comment]
Not fixed.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close.

**Comment by cyrus-gc** [comment]
Moved to Live. Fixed. Please verify and close.
