### ISSUE TITLE
Issues - 26th July 2016

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#104]
1. Highlight "Gender    Male     Female" in the signup forms for both Facebook and Email sign up modal windows if they are left unselected.
2. Update footer in the Sign up with Facebook email if the sign up happens without changing the email id associated with Facebook and in scenarios where the user adds a different notification email address.
3. When you show deactivation and reactivation modal windows, please remove references to "Can't find email after 24 hours...." and the "In the meanwhile,....". Please retain the line that asks the user to contact info@jodilogik.com
4. The tool tip for workload box in Profession section has to be round.
5. The Family and beliefs section text box formatting in edit mode needs to fixed.
6. We have made some improvements notification is not required for this release. Please dont show old notifications.
7. When the profile owner changes password, fix the bug in the email we send to the guest where the guest can send an email requesting the password. The email should always have the notification email associated with the profile owner who may have signed up with Facebook and chose a different notification email.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.

**Comment by mailanand75** [comment]
An interesting new issue came up when I tested.

I deactivated my profile and clicked on the confirmation email. I was asked to click on the reactivation link.

Now I refreshed the page and this is what I saw:

![image](https://cloud.githubusercontent.com/assets/12179089/18615644/95a81cda-7dc9-11e6-8a8f-80a948f28957.png)

**Comment by cyrus-gc** [comment]
Fixed and Please check this in Staging.
