### ISSUE TITLE
Deactivate email sent twice?

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#105]
Please find out why this user received deactivation requests twice: rameshwara001@gmail.com

**Comment by cyrus-gc** [comment]
It's Not Reproducible, Please check again and confirm.

**Comment by mailanand75** [comment]
May I know why the email was sent twice for the email id rameshwara001@gmail.com ? It's not a question of reproducing the bug. We have evidence of the bug showing up.

**Comment by cyrus-gc** [comment]
The possiblity here is that the user can request to deactivate his profile many times unless he clicks the DEACTIVATE LINK from the request mail recevied earlier. Once the deactivation is confirmed ( clicking the deactivate link from his mail inbox ), then the user cannot request for deactivation any more.
