### ISSUE TITLE
Pending Issues

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#106]
1. Mobile portrait mode (edit profile) -Size of the Partner expectation dropdown boxes not correct.
2. Fonts used and size of the boxes for Boxzilla needs correction.
3. A customer signed up with Facebook and with email using the same email id - er_sanketsuthar@yahoo.com
4. I am unable to locate the signup emails for these two people who deactivated:
   ashishpandey52@gmail.com
   nickmathur@gmail.com
5. The user with the email id prembrijwani@gmail.com did not have the first name or the last name in Mailchimp. I manually added the first name.
6. I updated the profile on the production server (mailanand75@yahoo.com) by adding a horoscope (17 Aug). The update notification was never sent.
7. Homepage - Under "Why Sign Up", first panel, change "signup with email" to "sign up with..."
8. Homepage - Under "Why Sign Up", last panel, please add a space between Jodi and Logik.
9. imhimani24@gmail.com received two profile update notifications on Sep 1st from the same profile. The 24 hour rule is not working.

**Comment by cyrus-gc** [comment]
point 1,2, 7 and 8 are fixed. point 3 - er_sanketsuthar@yahoo.com has signed up with email only and not via Facebook. 
4 - both the profiles are joined through facebook so , there will not be any signup emails for them.
6 - disabled profile update notification for mailanand75 profile updates
5 and 9 - we have the separate github issues on this and we can track it.
Please close this defect.
