### ISSUE TITLE
Plus Sign on Lifestyle Images in Profile View

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#11]
When I view a profile I see a plus sign on the lifestyle images that is off center. Showing plus sign indicates new images can be added. In the profile view, this is misleading. Please remove the plus sign in profile view.

If at all a icon has to be retained, use the expand icon seen in video sites such as YouTube. This has to be uniformly applicable to all instances in all sections where expanded view of the photograph is allowed.

The screenshot below is from Edge browser.

![image](https://cloud.githubusercontent.com/assets/12179089/9581237/ce008806-501b-11e5-9df6-7f7fe57fbabd.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this.

**Comment by mailanand75** [comment]
closed.
