### ISSUE TITLE
Typo Fixes In Men's Guide - Resources

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#112]
Chapter 1:
1. "Let's rewind to a few years when you graduated from college."
   Correction: Replace "years" with "years ago".
2. "The first thing you probably did was to create your biodata or resume." 
   Correction: Add a comma after "probably did".
3. "What if one of them was the right one for you, but you never had a chance to meet that individual because they thought your biodata was unappealing?" 
   Correction: Add a comma after "that individual".
4. "This is true even when we see photographs."
   Correction: Add a comma after "true".
5. "The power of first impression is hard to change and your biodata for marriage should leave a positive impression."
   Correction:Replace "first" with the "first".
6. This guide will give you a step by step guidance to create a biodata for marriage that will dramatically improve the chances of creating a great first impression and thereby increasing the possibility of meeting the girl of your dreams.
   Correction: Replace "increasing" with "increase".

Chapter 2:
1. "Telling a story that brings out your personality is not easy, but if done right, can make your matrimonial biodata stand out from the crowd of uninspiring and stereotyped biodata that people general end up writing."
   Correction: Add a comma after "stereotyped biodata".
2. "When you are describing yourself in your biodata for marriage, first write it down in a piece of paper and when you are satisfied with what you have written, share it with your sister, mother or even friends."
   Correction: Replace "down in: with "down on".
3. "Software Engineer with a sense of humour"
   Correction: Replace "humour" with "humor".
4. "My job also keeps me on my toes, as I am always trying to learn new skills to keep pace with the changing technology landscape."
   Correction: Replace "My job also keeps" with "It also keeps".

Chapter 3:
1. "We are conditioned by print, television and movies to falling in love with beautiful women who seem to have a tendency to fall in love at the drop of a hat or other flimsy excuses."
   Correction: Add a comma after "television".
2. "On the other end of the spectrum, men with low self-esteem or with a poor self-image tend to settle for anyone as long as they are from the opposite sex."
   Correction: Replace "are from" with "are of".
3. ""Looking for a girl with MBA, Marketing that can cook and take care of the elders.." is a great way to show that you are a male chauvinist with outdated expectations and total disregard for women. It's time to grow-up."
   Correction: Add a comma after "Marketing" and "can cook".

Chapter 4:
1. "You fell in love with your photograph taken years ago and very soon it becomes your "go to" photograph for all your social media profiles."
   Correction: 
   Replace "photograph taken" with "photograph that was taken".
   Add a comma after "years ago" and after "very soon".
2. "You may be tempted to use the same photograph for your biodata for marriage as well."
   Correction: Replace "biodata" with "biodata, and".
3. "This research study involved showing a group of people a set of unfamiliar faces for just a fraction of a second."
   Correction: Add a comma after "of people".
4. "Both the groups had similar ratings for the unfamiliar faces irrespective of how long they looked at the photographs!"
   Correction: Add a comma after "unfamiliar faces".
5. "But make sure you don't include four different headshots and nothing else as it conveys the impression that you are hiding something."
   Correction: Add a comma after "But" and after "nothing else".
6. "According to Roman Griffen, author of Internet Dating: Tips, Tricks and Tactics. "When the picture you post was taken from across the street, the purpose of posting it-letting people see what you look like-is defeated"."
   Correction: 
   Add a comma after "Tricks".
   Replace "it-letting" with "it lets".
   Replace "like-is" with "like is".
7. "Never include photographs that's over a year old in your biodata for marriage or in your online matrimony profile."
   Correction: Replace "that's" with "that're".
8. "Imagine you love the photo of a girl, but when you see her in person, she is not the body type you imagined."
   Correction: Add a comma after "Imagine".
9. "Also, make sure you are not wearing sun glasses or a hat in at least one photograph unless you are a detective by profession!"
   Correction: Replace "sun glasses" with "sunglasses".
10. "If the online matrimony site that you might have enrolled in allows you to include additional photographs, select the ones that shows you doing what you love."
    Correction: Replace "shows" with "show".
11. "Let's say you have claimed in your matrimony profile that you are into skydiving. Make sure there is one photograph to prove your claim!"
    Correction: Add a comma after "say".
12. "According to this blog, Apps like Camera+ (iOS) and ProCapture Free (Android) have additional features alongside the normal phone settings. Others have more specialized functions like Slow Shutter Cam (iOS), Night Cam and Pro HDR (iOS, Android)."
    Correction: Replace "Apps" with "apps".
13. "Walking into any of the photo studios in your town or city randomly is not a great idea as you never know the quality of photographers they may have."
    Correction: Add a comma after "great idea". 

Chapter 5:
1. "According to Kate Houston, founder of the profile-writing servicetrysweettalk,"
   Correction: Replace "servicetrysweettalk," with "service trysweettalk".
2. "If you think the word alcoholism should be avoided, you should also avoid mentioning things like "I live and breathe work", "my job is my first wife" and other self-defeating statements."
   Correction: Replace "word alcoholism" with "word "alcoholism"".
3. "If you are a Nobel Prize winner, a mere hint would do or you could include a photograph of you receiving the coveted prize (if the online matrimony site allows you to do so). 
   Correction" Add a comma after "would do".
4. "But don't brag about it either."
   Correction: Add a comma after "But".
5. "Never mention how much you earn in your biodata for marriage no matter what others do or think you should be doing."
   Correction: Add a comma after "for marriage".

Chapter 6:
1. "Matchmaking happened through your family or through marriage brokers who roamed the far corners of the country with a dozen photographs of boys and girls and we were all using Windows 95!"
   Correction: Add a comma after "and girls".
2. "One of the first things our parents did then or made us work on was to create a one-page or a two-page biodata for marriage."
   Correction: Add a comma after "work on".
3. "Keep this brief, for after all, it's your biodata for marriage."
   Correction: Add a comma after "for".
4. "A group photograph is a great idea to give women a good sense of what she might be signing up for. "
   Correction: Add a comma after "women".

Chapter 7:
1. "This is a question men need to understand better in order to create an impactful biodata for marriage."

Correction: Add "that" after "a question". 
1. "While women and their families may not explicitly review their choices of men against all these factors consciously, it helps men to be aware of inherent and subconscious thought processes that drives decision making among women and their families."
   Correction: Replace "drives" with "drive".

Chapter 8:
1. "The secret to finding a perfect match is to be open and honest about yourself in your matrimonial biodata. Pay attention to small details like spelling, grammar and formatting."
   Correction: Add a comma after "grammar".
2. "Treat your biodata for marriage as a first step in an important journey."
   Correction: Replace "as a" with "as the".
3. "While these may be important, they don't gurantee a successful marriage."
   Correction: Replace "gurantee" with "guarantee".
4. "If you think just writing your biodata can attract the right set of prospective matches, you fall short miserably."
   Correction: Add a comma after "you think".
5. There is no way a biodata for marriage that only showcases just data can improve your chances of finding your soulmate as you will have to depend on a lucky break to meet someone suitable.
   Correction: Add a comma after "no way".
6. "Going back to point 1 in this list, it is unwise to be willingly treated as a product or a commodity and then hope that the person you meet actually turns out to be your soulmate!"
   Correction: Replace "point 1 in" with "point 1 on".

**Comment by cyrus-gc** [comment]
Fixed. Please Check in Staging Server.
