### ISSUE TITLE
Typos in Women's Guide

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#113]
Chapter 1:
1. "Even if you choose to enroll in an online matrimony site or place an advertisement on the newspaper, prospective matches and their families will insist on seeing your matrimony biodata."

Correction: Replace "on" with "in" and add a comma after "matches".

Chapter 2:
1. "Newspapers and online matrimony sites takes away this advantage and you are reduced to using emoticons, punctuation marks, acronyms and capitalized text to projecting yourself."

Correction: Replace "takes" with "take".
1. "Lack of self-confidence can turn off men and do become a major issue in sustaining relationships." 

Correction: Replace "do become" with "thus becomes".
1. "Telling a story involves three key components - A protagonist (that is you), the challenges you have overcome (such as winning in school or professional achievements), and the adventures you love to embrace (your likes, interests)."

Correction: Replace "winning" with "getting accolades".
1. "Reading has also stoked my passion for travel as I end-up discovering new books everywhere I go!"

Correction: Replace "end-up" with "end up".
1. "My job as a journalist for The Hindu, allows me to pursue the twin interests of books and travel, and I consider it as a blessing to have a career aligned to my interests." 

Correction: Replace "aligned to" with "aligned with".
1. "As you can imagine, reading books and traveling has made me a happy-go-lucky person with a positive outlook to life."

Correction: Replace "outlook to" with "outlook on".
1. " Several of my family members work for the armed forces and I value their sense of commitment, honesty and love for the country."

Correction: Add a comma after "honesty".

Chapter 3:
1. "This is a trap you should avoid at all costs."
   Correction: Replace "trap" with "trap that".
2. "It's important to keep of a list of non-negotiable items ready."
   Correction: Delete "of".
3. "Most biodata for marriage tend to rely on clichés."
   Correction: Replace "tend" with "tends".
4. "You should be willing to also put up with my dog and be open to adopting more of the four legged kind once we settle down."
   Correction: Replace "four legged" with "four-legged" and "kind" with "kinds".
5. "I have a modern outlook to life but I believe in traditional values such as respect for parents and helping others in need."
   Correction: Replace "outlook to" with "outlook on".
6. "I am willing to change my opinions if you can convince me and and you should be open-minded about your opinions as well."
   Correction: Replace "and and" with "and".

Chapter 4:
1. "Pour your heart and soul in getting this right, so that you can increase your chances of getting a response. "
   Correction: Replace "soul in" with "soul into".
2. "Spending longer time doesn't really change our opinion. This was the conclusion from their research titled "First Impressions"."
   Correction: Replace "Spending longer" with "Spending a longer".
3. "This research study involved showing a group of people a set of unfamiliar faces for just a fraction of a second."
   Correction: Add a comma after "faces".
4. "Both the groups had similar ratings for the unfamiliar faces irrespective of how long they looked at the photographs!"
   Correction: Add a comma after "faces".
5. "But make sure you don't include four different headshots and nothing else as it conveys the impression that you are hiding something."
   Correction: Add a comma after "else".
6. "According to Roman Griffen, author of Internet Dating: Tips, Tricks and Tactics. "When the picture you post was taken from across the street, the purpose of posting it-letting people see what you look like-is defeated"."
   Correction: 
   Add a comma after "Tricks" and replace the period after "Tactics" with a comma. 
   Replace "When" with "when". Replace "it-letting" with "it letting". 
   Replace "like-is" with "like is".
7. "A study by Rory McGloin (Assistant Professor in the Department of Communication at the University of Connecticut) and his colleagues has shown that people, in general, prefer "enhanced photographs" - the ones with better lighting, hair and makeup."
   Correction: Add a comma after "hair".
8. ""You look at a picture of someone and all of a sudden you're making judgments about what their personality is like, what their values are, whether or you want to go on a date with them or even maybe spend the rest of your life with them"."
   Correction: Add a comma after "sudden".
9. "Please don't skip on adding photographs as this is your best shot in attracting the right set of prospective candidates."
   Correction: Replace "shot in" with "shot at".
10. "A dangling telephone wire, a bad patch of paint on the wall, an open cupboard revealing all its messy contents or even a misplaced book can ruin a perfectly good profile photograph otherwise."
    Correction: Add a comma after "contents".

Chapter 5:
1. "No matter what women end up eventually doing after marriage, men expect their wives to have a great educational background or at least a comparable education qualification."
   Correction: Add a comma after "background".
2. "Yes, the idea about what a women should be in a marriage has changed even in India."
   Correction: 
   Replace "idea about" with "idea of".
   Replace "a women" with "women".
3. "A cardinal sin that women end up committing is to play down their professional ambition for fear of turning off men."
   Correction: Add a comma after "committing".

Chapter 6:
1. "So what do men look for when they look at a biodata for marriage from a woman?"
   Correction: Add a comma after "So".
2. "Some researchers have attempted to find answers for this question, and we decided to bring to you the results of what we believe to be the most objective of the studies."
   Correction: Replace "answers for" with "answers to".
3. "The users were fitted with eye-tracking device that monitored the eye movement as the users browsed various online profiles."
   Correction: 
   Replace "eye-tracking" with "an eye-tracking".
   Add a comma after "movement".
4. "The tracking device created visual hotspots on the screens (called heatmaps) to show where users spent more time and the order in which users read the profile."
   Correction: 
   Replace "heatmaps" with heat maps".
   Add a comma after "(heat maps)".
5. "Both men and women in the study also felt that when they read descriptive explanations on what the expectations are from the opposite sex, it helps them in deciding on the suitability of initiating a conversation."
   Correction: Replace "from" with "of".
6. "For men, the profile photograph is shaded red, indicating more amount of time spent by men viewing the profile photograph of the woman."
   Correction: Add a comma after "red".
7. "The conclusion is simple, if you are a woman, spend all your time and energy in getting the profile photographs right."
   Correction:
   Replace "simple," with "simple."
   Replace "if" with "If".

Chapter 7:
1. "The secret to finding your soulmate is to be aware of inherent and subconscious thought processes that drives decision making among men and their families when it comes to marriages."
Correction: Replace "drives" with "drive".
1. "Pay attention to small details like spelling, grammar and formatting."
   Correction: Add a comma after "grammar".
2. "Treat your biodata for marriage as a first step in an important journey."
   Correction: Replace "a first" with 'the first".
3. "While these may be important, they don't gurantee a successful marriage."
   Correction: Replace "gurantee" with "guarantee".
4. "There is no way a biodata for marriage that only showcases just data can improve your chances of finding your soulmate as you will have to depend on a lucky break to meet someone suitable."
   Correction: Remove "just" from this sentence.
5. "There is no way a biodata for marriage that only showcases data can improve your chances of finding your soulmate as you will have to depend on a lucky break to meet someone suitable."
   Correction: Add a comma after "soulmate".

**Comment by cyrus-gc** [comment]
Fixed. Please Check in Staging Server.
