### ISSUE TITLE
Clicking on Reply from email

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#116]
When you send a chat notification email, the email has a Reply button embedded in it. When the user clicks on it, the button should take the user to the login modal window or directly open the profile if the user is already logged in. In the current version, we are showing the homepage.

**Comment by cyrus-gc** [comment]
Fixed and Please test in Staging.

We have redirected the user to Login Modal window when clicking the reply button.

**Comment by cyrus-gc** [comment]
Moved to Live. Fixed. Please verify and close.

**Comment by mailanand75** [comment]
I tried testing the fix. So I logged into an account associated with mailanand75@yahoo.com and sent a message to Ashok Kumar (ashok600042@gmail.com) and a message to Cyrus @ glasscheese. I logged out. I did not see any communication notification email go out. Is this is a new bug?

**Comment by cyrus-gc** [comment]
The communication emails are sent out. The LIVE DB has been downloaded locally and tested thoroughly. This issue is not reproducible. Please check this once and close this issue.

**Comment by mailanand75** [comment]
I tested it again, this time I sent messages to bhattdarshan13491@gmail.com and I did not see the communication notification.
