### ISSUE TITLE
Deactivate Submit Button To Be Center Aligned

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#12]
The deactivate submit button has to be center aligned to the text area above the button.

![image](https://cloud.githubusercontent.com/assets/12179089/9581541/b389e7ae-501d-11e5-93af-91b20bd5505c.png)

**Comment by cyrus-gc** [comment]
This works fine on a desktop and in smartphones. However, we have tweaked the code this to work on all screen resolutions. This is fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
closed.
