### ISSUE TITLE
Gmail confirmation email finder not seen

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#122]
When a user signs up with gmail, we are supposed to show a button that will take the user directly to the email on Gmail. This feature is missing?

![image](https://cloud.githubusercontent.com/assets/12179089/19849606/3a86556a-9f7a-11e6-8c95-0aaa5e1d9d60.png)

**Comment by cyrus-gc** [comment]
Fixed and updated in LIVE
