### ISSUE TITLE
Error in the Reactivate Modal Window

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#14]
I deactivated my profile. I then open the homepage and clicked on Join With Facebook button saw this message:

Please note that when we dont send email, please DO NOT ask to check for email or talk about following us on Facebook and Twitter.

![image](https://cloud.githubusercontent.com/assets/12179089/9581727/cd902f90-501e-11e5-8146-4c1a0b54637f.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
Closed.
