### ISSUE TITLE
UI Issues on portrait and landscape modes - Moto X Gen 2

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#15]
![image](https://cloud.githubusercontent.com/assets/12179089/9583296/2e4a5618-5028-11e5-8153-a7465199c76e.png)

![image](https://cloud.githubusercontent.com/assets/12179089/9583319/461982a0-5028-11e5-8653-21a604cbceda.png)

![image](https://cloud.githubusercontent.com/assets/12179089/9583331/5e165b08-5028-11e5-8e64-0ebe4daadb4e.png)

On mobile phone, the video pause button doesnt disappear.
![image](https://cloud.githubusercontent.com/assets/12179089/9583372/945fc8ac-5028-11e5-8453-2273d2aa0283.png)

![image](https://cloud.githubusercontent.com/assets/12179089/9583393/b0e2efa4-5028-11e5-81c9-765cde631c1b.png)

![image](https://cloud.githubusercontent.com/assets/12179089/9583409/cb34c45e-5028-11e5-8fe7-28cb1cfbe910.png)

**Comment by mailanand75** [comment]
This issue is same as what I have reported in #2

**Comment by cyrus-gc** [comment]
All issues are fixed as listed above except for the video player PAUSE button. We need to have a different approach on mobile platforms for a PLAY / PAUSE buttons. By Friday, we will do a release on this.

**Comment by mailanand75** [comment]
All issues are fixed except the issue of not vertically center aligning the rows of names / email ids / number of views / status table under "Share Profile" and one other new issue (see the second screenshot below)

![image](https://cloud.githubusercontent.com/assets/12179089/9909401/af7cb188-5cb5-11e5-84c7-adb0fda667a0.png)

One new issue seen in landscape mode: The uploaded images in the profile edit mode and the delete image icons are not together.

![image](https://cloud.githubusercontent.com/assets/12179089/9909449/e0552ede-5cb5-11e5-90db-e2180085b1e4.png)

**Comment by mailanand75** [comment]
Please also look for inconsistent spacing between menu items in the hamburger icon in both portrait and landscape modes.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this.

**Comment by mailanand75** [comment]
All the above items are fixed. Thanks.

However, now the themes are all distorted both in portrait and landscape modes. Attaching the portrait mode.

![image](https://cloud.githubusercontent.com/assets/12179089/10096075/4d4107fc-638c-11e5-8889-7352266b1f84.png)
