### ISSUE TITLE
Blog Admin URL and Image location URL Needs to Migrated To Jodilogik.com domain a

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#16]
The blog admin URL continues to be http://104.209.44.117/wordpress/wp-login.php

Also, images uploaded to Wordpress need to be migrated so that their location is in the Jodilogik.com domain as opposed to http://104.209.44.117.

**Comment by cyrus-gc** [comment]
This is automatically fixed since the admin works on www.jodilogik.com instead of the IP address. Please verify and close this issue.

**Comment by mailanand75** [comment]
Closed.
