### ISSUE TITLE
Blog Page Formatting Issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#17]
This is how my blog page appears in the absence of any post in my Chrome browser on a 13 inch laptop.

![image](https://cloud.githubusercontent.com/assets/12179089/9597421/1cc58148-509f-11e5-8924-011576b86cac.png)

**Comment by cyrus-gc** [comment]
Even if we clear the post, what we see is the blog title and the primary widget. You may need to clear this too in the admin panel. Let me know what fix we need to do here.

**Comment by mailanand75** [comment]
I don't mind seeing this widget. Wondering why the widget formatting for the email text box has done haywire.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
closed.
