### ISSUE TITLE
Access Denied Page

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#18]
In the access denied page (devil with lock), the link to request access is not working.

**Comment by cyrus-gc** [comment]
We dont have the workflow for this scenario. We have also raised this through emails before. Ideally the link should send an email to the profile owner to grant the recipient access. We have identified this use case to be implemented in the next phase. Let me know if we can do something real quick for this release.

**Comment by mailanand75** [comment]
No, remove the link to request access. We will take this up in the next phase if its not in the cope of work already. Please confirm once the link is removed.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
Closed
