### ISSUE TITLE
Footer in blog page

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#19]
The footer in the blog page doesnt seem to extend all the way. This is not a major issue, just feel odd to see the inconsistency.

![image](https://cloud.githubusercontent.com/assets/12179089/9623973/dcc2c3a4-5165-11e5-8ac7-04dc2e3a45a7.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
Closed.
