### ISSUE TITLE
Alignment issues for mobile broswers

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#2]
1. Both portrait and landscape modes when using Share Profile and Invite Friends needs corrections for proper alignment and usability.
2. The hamburger menu icon in landscape mode gets on top of the header menu items in the landscape mode.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this defect.

**Comment by mailanand75** [comment]
I don't see the fix. I cleared the browser cache and tried again. Getting the same issues.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
The issues dont appear to be fixed, In fact, additional formatting issues have now cropped up!

**Comment by mailanand75** [comment]
Here is the landscape mode for invite friends 

![image](https://cloud.githubusercontent.com/assets/12179089/9830009/60c6a976-593c-11e5-87c7-4786171f4b57.png)

Landscape mode for profile edit page - notice the menu
![image](https://cloud.githubusercontent.com/assets/12179089/9830014/8cd79d0e-593c-11e5-89c2-cadd36a844ae.png)

Portrait mode for share profile - notice the middle row is not center aligned.

![image](https://cloud.githubusercontent.com/assets/12179089/9830020/ca567e5c-593c-11e5-9ee4-b07fad608af7.png)

About Us page in landscape mode. notice the hamburger menu.

![image](https://cloud.githubusercontent.com/assets/12179089/9830030/0dd04a32-593d-11e5-9897-be8828f25c0d.png)

This is the deactivate feature in landscape mode

![image](https://cloud.githubusercontent.com/assets/12179089/9830064/f781cb1a-593d-11e5-876c-883eb8f45460.png)

And finally, noticed that the images uploaded to "Family" in the edit mode continues to be slightly distorted. This is hapenning only in the Profile edit page. Profile View is fine.

**Comment by cyrus-gc** [comment]
Fixed all issues listed above. Please check.
