### ISSUE TITLE
Clicking on Deactivate on mobile browser (Moto X Gen2) doesn't take me to Deactivate panel

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#21]
After I click deactivate on my mobile chrome browser, and navigate away to some other panel, i clicked on deactivate again. This time, its not taking me back to the deactivate panel.

**Comment by mailanand75** [comment]
BTW this error happens only on Landscape mode. The portrait mode works fine.

Can you also check all links work on portrait and landscape modes?

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
