### ISSUE TITLE
Footer not aligned in Deactivate Devil Screen - Desktop and Mobile (Portrait mode)

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#22]
Please push the footer all the way to the bottom of the screen in the Disable Access screen on both portrait mode in mobile browsers as well as on Desktop. Landscape on mobile browsers works fine.

![screenshot_2015-09-04-17-58-51 1](https://cloud.githubusercontent.com/assets/12179089/9683936/009e71d8-5332-11e5-99c3-fcda9e6094d7.png)

**Comment by cyrus-gc** [comment]
Fixed.

**Comment by mailanand75** [comment]
closed.
