### ISSUE TITLE
Please review this message from Facebook

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#25]
Can you please let me know what needs to be done for this alert?

![image](https://cloud.githubusercontent.com/assets/12179089/9717047/f21cf1ae-558c-11e5-98bd-665e06fb1ff9.png)

**Comment by mailanand75** [comment]
Here is the link that opens up when you click on the link embedded in the alert message.

https://developers.facebook.com/docs/facebook-login/security

**Comment by cyrus-gc** [comment]
Fixed. There is a URL textbox right down the same screen. We need to fill that with jodilogik URL. Done.

**Comment by mailanand75** [comment]
Closed
