### ISSUE TITLE
404 Page alignment Issue - Desktop

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#26]
Please align the box that contains the text "Take me back to Home" with the yellow 404 box above. Both these boxes should have the same width.
![image](https://cloud.githubusercontent.com/assets/12179089/9791769/5fea1774-57fa-11e5-80b7-8ccef5667fe8.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
