### ISSUE TITLE
404 Page formatting issue on smartphones - Portrait

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#27]
This is the portrait mode for the 404 page on Moto X 2nd gen phone.

![image](https://cloud.githubusercontent.com/assets/12179089/9792046/d2454d6a-57fb-11e5-92bb-67478e1c894a.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
The formatting issue with the text and the box is now resolved. However, the image shows up only in one half of the screen as before.

**Comment by cyrus-gc** [comment]
Fixed. Please verify.

**Comment by mailanand75** [comment]
Looks lovely! Closed.
