### ISSUE TITLE
Unsubscribe - Subject and notification issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#29]
The unsubscribe functionality is a stop gap arrangement till we have mailchimp in place.

When the user clicks on any unsubscribe links from emails, please open the user's mail client with the subject "Unsubscribe" and the default text as "I would like to opt out of receviving further messages from Jodi Logik."

The admin alone should receive a notification that says <name>, <email id> has opted out of <email name>. The subject for this notification email to the admin will be "unsubscribe notification".

**Comment by mailanand75** [comment]
The admin alone should receive a notification that says name of the person has opted out of email name. The subject for this notification email to the admin will be "unsubscribe notification".

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
The default email for he user wanting to unsubscribe is correct. However the admin did not receive any information on the name of the user and from which email did the user unsubscribe from.

**Comment by cyrus-gc** [comment]
We have added additional timestamp to the unsubscribe email to pick the email from the info@jodilogik Sent mailbox. Please check and close this issue.

**Comment by mailanand75** [comment]
Actually, this is not what I had explained above and in my email. But looks like this is the only possible solution. Can you add the text "Please do not delete this text:" just before the text that says "<name> has  opted out of............................... 

I am closing this.
