### ISSUE TITLE
New Message Screen

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#31]
Under what circumstance / test case do we show this screen? May I know why this is in a completely new format and the footer showing up in the middle of the screen?

![image](https://cloud.githubusercontent.com/assets/12179089/9883494/0a6e5614-5bf8-11e5-8665-95c27c35e31c.png)

**Comment by cyrus-gc** [comment]
This screen will be displayed for any Exception that is throw in the code like stack trace errors. We can push the footer down. Let me know if you have a image / any other way this page needs to be formatted.

**Comment by mailanand75** [comment]
Please push the footer to the footer area. Are there any other hidden application message screens that I am not aware of?

**Comment by cyrus-gc** [comment]
There are no other screens like this.

**Comment by mailanand75** [comment]
OK. Thanks. i will close this once you confirm the footer issue is addressed.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
