### ISSUE TITLE
30 Sec+  Response Time For Profile Edit and Profile View Pages

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#37]
The response time for loading the profile edit and profile pages are way off the mark. I don't think customers will have tha patience for the pages to load.

Please start testing the application on 512 kbps lines. Thats the most you can expect.

The entire page seems to download in one go and that might be the reason for the poor response times.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
