### ISSUE TITLE
Delay in sending email invites and other emails

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#40]
I had a demo of the application last night. It took about 30 minutes for the profile invitation email to reach the recipient. Same problem with stop access message.

**Comment by cyrus-gc** [comment]
It seems that ZOHO email server is slow to send emails from the SMTP port. JL application uses SMTP to send emails. Local testing of the same code using the email jodilogik@gmail.com send emails instantly. We need to ping Mahi if he can provide some help on this.
