### ISSUE TITLE
Send Reminder For Invitation to Join JL - Errors in the message and email

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#42]
I tested the "Send Reminder" feature under invite friends.
Please fix the following errors:
1. The message to be displayed within the application on clicking "send reminder" under should be "We have sent a reminder to <name of the recipient>. Thank you!"
2. The email that we send to the recipient should be:

Hi <name of the recipient>

<Name of the sender> has sent you a reminder about the invitation to join Jodi Logik.

<Yes, Create My Jodi Logik Profile>

Please talk to <name of the sender> about Jodi Logik or send an email to info@jodilogik.com for more information.

Regards,
Jodi Logik Minions

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
