### ISSUE TITLE
Session Management Issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#44]
When I log into Jodi Logik and remain inactive for a long time, the session expires. However, session expiry notice is not showing up on expiry of the session. Instead, the application waits for me to make a data entry and shows a custom error message which says, data is not saved (written with incomplete words) and then the application shows me a session expiry window. 

The user should not see the non-standard error message and the session expiry notice should show up immediately on session expiry and not wait for the user to attempt a data save.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
