### ISSUE TITLE
Message Formatting - Password update

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#45]
When a member changes the password for accessing Jodi Logik profile, the corresponding recipient of the email invite is informed about the password change. When you display a message to the profile owner informing that the application has informed the recipient of the password change and that the profile owner should still communicate the password directly to the recipient. When this message is displayed, please bring the last line in the message to the second line and center the last line along with the first line in the message? Right now, the lack of line break makes it look funny and difficult to read.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
