### ISSUE TITLE
Email subject correction for password request

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#46]
When a password to access a JL profile is changed, an email is sent to the person that had received access to the profile. From the email, this recipient can click on "Request new password from <name>" and send an email to the owner of the profile.

The subject line for this email is "Request new password for your Jodi Logik Profile". Please change the subject line to "Please share the updated password for your Jodi Logik profile"

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
