### ISSUE TITLE
Email received by admin for abuse notification

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#47]
Hi Cyrus

A minor correction is required in the email received by the admin when a user reports abuse.

Please change "Abused user profile" to "User profile with abusive content."

Reporting User Name :kannan
Reporting user Email Id :kannan.k@glasscheese.com
Abused user profile Link :http://www.jodilogik.com/home/viewProfileGuestUser/?profileId=dG9jeXJ1c0B5YWhvby5jb20=/a2FubmFuLmtAZ2xhc3NjaGVlc2UuY29t
Reporting user Comment :test data

Srini

On Tue, Oct 13, 2015 at 8:11 PM, Srinivas Krishnaswamy saleswhiz@gmail.com wrote:
Thanks Cyrus. Looks good.

Srini

On Oct 13, 2015 7:52 PM, "Cyrus" cyrus.s@glasscheese.com wrote:
Hi Srini,

Just now we have made a report abuse request of a jodilogik profile in LIVE.

Please check the email for further reference.

Regards,
Cyrus.S

On Tue, 13 Oct 2015 17:35:00 +0530, Srinivas Krishnaswamy saleswhiz@gmail.com wrote:

Hi Cyrus

Can you please report abuse through one of the test profiles? I would like to see how this email shows up for the admin.

Regards
Srini

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
