### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#5]
The Unsubscribe email doesnt tell the admin anything about the email from which the user unsubscribed. I know this is a temporary fix till I implement mailchimp, but I wanted to know if its too much work to identify the email from where the user clicked unsubscribed.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
This is same as issue #29. I will close this and keep #29 open.
