### ISSUE TITLE
Session Management Query

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#53]
When a member received a view profile invitation from another member, the member will see "Edit Your Profile" in the header when viewing the profile of another member. Right now, the session expires for the member who is viewing the profile of another member after a period of inactivity even though the member is not editing their own profile. Is this approach correct?

**Comment by cyrus-gc** [comment]
The approach is wrong. This is a defect. We have fixed this. Please verify and close this issue.
