### ISSUE TITLE
Test cases for handling deactivated and banned profiles

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#55]
Can you confirm we have the following test cases

1.A Jodi Logik member has shared his profile to multiple people and has had multiple conversations through the heart icon. The profile owner deactivates his profile. 
- Scenario A: When the profile viewer clicks on the invitation link to view the profile, the application should should show the devil page. 
- Scenario B: When the profile viewer is chatting with the profile owner and doesnt close the browser window. The profile owner (in a fit of rage) deactivates the profile when the chat is in progress. How will the application handle this scenario.
1. Same point as above, but just that the profile owner is banned. Apply scenario A and B.
2. What happens when a Jodi Logik member shares his profile with a deactivated user. When the deactivated user views the profile, the application shouls not say, you can create your profile. It should show a "Reactivate Profile" button instead of log in button?

**Comment by mailanand75** [comment]
Cyrus - can we discuss these points so I know how the application handles them? I will close this once I hear from you.

**Comment by cyrus-gc** [comment]
Point #1 is there in the current build.
Point # 2 is not there. We will take this as an enhancement in the next sprint.
