### ISSUE TITLE
Handling name field when downloading the Men's and women's guides

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#57]
Here is how the email was sent to this user for downloading the access to the men's guide: We need to make sure name field only allows hyphen and alphabets to be used.

![image](https://cloud.githubusercontent.com/assets/12179089/15646404/0e1e01b2-267b-11e6-970c-293354b2e5b9.png)

**Comment by cyrus-gc** [comment]
Fixed.
