### ISSUE TITLE
Gmail landscape mode issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#61]
When our emails are viewed in landscape mode on gmail, the logo and the social media icons are not properly centered.

**Comment by cyrus-gc** [comment]
Works as intended.
![gmail_landscape](https://cloud.githubusercontent.com/assets/12209741/15814130/08e245ca-2be2-11e6-990d-1b9b96a16033.png)

**Comment by mailanand75** [comment]
Not fixed. Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/12179089/15821790/9c1e00f4-2c0f-11e6-97ea-0ad377c6d4ec.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.
