### ISSUE TITLE
Message shown in modal window once a password reset link is sent

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#63]
![image](https://cloud.githubusercontent.com/assets/12179089/15672785/6045c936-2750-11e6-90b9-01a9a62dda51.png)

The message shown in the modal window when the reset password request is successfully submitted should be changed to:

We have sent you an email with instructions to reset your password. Please check your email inbox now.

**Comment by cyrus-gc** [comment]
Fixed
