### ISSUE TITLE
Did not receive the report abuse notification

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#70]
I did not receive the report abuse notification.

**Comment by cyrus-gc** [comment]
The mails should reach staging@jodilogik.com. Did you check in this mailbox?

**Comment by mailanand75** [comment]
Yes

**Comment by mailanand75** [comment]
Sorry, closed it by mistake

**Comment by cyrus-gc** [comment]
Works as intended. Mails are hitting the inbox of staging.
