### ISSUE TITLE
Email formatting as per standards

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#71]
Issue 3b reported on April 21, 2016, is open while it is marked as closed. Here is  a screenshot from my gmail inbox

![image](https://cloud.githubusercontent.com/assets/12179089/15676457/dc9886fa-2763-11e6-9f58-ebc6da59c844.png)

**Comment by cyrus-gc** [comment]
Fixed.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.
