### ISSUE TITLE
Point 5 reported on May 4, 2015 is open

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#78]
I tried uploading a text file for horoscope and i got a message that told me the document was empty eventhought it was not.

**Comment by cyrus-gc** [comment]
We have made the minimum file size to be 15KB for any horoscope to have some information in it. We need to change the error message accordingly like "You have provided very less information on your horoscope. Please upload your updated horoscope with more details". Please advise.

**Comment by mailanand75** [comment]
Anything greater than 0 kb, we should not bother to say anything to the user. If I upload an empty file in a format that is allowed for horoscope, just check (where possible) if it is 0kb and show the message relevant for such instances.

**Comment by cyrus-gc** [comment]
Fixed
