### ISSUE TITLE
Password entry modal window for profile view by guest 

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#79]
The modal window to enter the password to access a Jodi Logik profile is not positioned properly in landscape mode on mobile devices.

**Comment by cyrus-gc** [comment]
![password_popup](https://cloud.githubusercontent.com/assets/12209741/15814152/4ef4fc4c-2be2-11e6-8f08-dd40e9736004.png)
![password_popup_2](https://cloud.githubusercontent.com/assets/12209741/15814153/4ef557be-2be2-11e6-974f-b6ccb7681c95.png)

Fixed alignment issues. Please test this and upload any screenshots if there is positioning issues still.
