### ISSUE TITLE
Error Message for Missing Email ID from Facebook API

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#8]
The error message that shows up when the user deliberately disallows access to email id when signing up has errors:

The error message title should be changed to "We need your email address."

In the body of the message, please remove "Can't find an email after 24 hours.....all the way including Facebook and Twitter icons." retain the core message as it is.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.

**Comment by mailanand75** [comment]
closed
