### ISSUE TITLE
Permanently delete invitee after 30 days

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#81]
We need to delete the guest from the Share Profile tray 30 days after the access is stopped by the profile owner.

**Comment by cyrus-gc** [comment]
We will take this in the next sprint as an enhancement.

**Comment by mailanand75** [comment]
I think we need to treat this is as a bug. This was the business logic we wanted to implement in the first place. If it is not implemented, it is an error that needs a fix.

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.
