### ISSUE TITLE
Report abuse email to admin

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#82]
When you send the report abuse email to admin, please make the following corrections in the email:

"Abuse notification from : Srinivas
Email of the party : saleswhiz@gmail.com
Comment : inappropriate images
Offending profile Link : http://www.jodilogik.com/home/viewProfileGuestUser/?profileId=bWFpbGFuYW5kNzVAeWFob28uY29t/aW5mb0Bqb2RpbG9naWsuY29t"

Cyrus - When the admin view the profile of a person, will this be trackable by the profile owner? In the sense, will the admin's email ID be added to the Share Profile tray with the number of views?

**Comment by cyrus-gc** [comment]
Fixed. The admin email ID will not be added to the Share profile list of the profile owner at all.
