### ISSUE TITLE
Modal window for gathering gender and who you are creating a profile for

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#83]
The modal window used to gather information on who you are creating a profile for and the gender is not formatted properly in landscape mode on mobile devices.

**Comment by cyrus-gc** [comment]
Works as intended.
![profilefor_gender_1](https://cloud.githubusercontent.com/assets/12209741/15814179/81f7377c-2be2-11e6-91e9-34431848f844.png)
![profilefor_gender_2](https://cloud.githubusercontent.com/assets/12209741/15814180/8221719a-2be2-11e6-9a9e-78be5e61cd73.png)

**Comment by mailanand75** [comment]
Not fixed. Please see the modal window below.

![image](https://cloud.githubusercontent.com/assets/12179089/15821131/8e3de728-2c0b-11e6-8e61-9c6e0ed6da1f.png)

**Comment by cyrus-gc** [comment]
Fixed
