### ISSUE TITLE
Theme selection and data save issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#85]
Theme selection did not work properly. The save animation was on for almost 4 minutes and after that it stopped and no background was applied. The problem with these issues is that you may not be able to reproduce them. Not sure who to fix these issues.

![image](https://cloud.githubusercontent.com/assets/12179089/15989552/dba0f9da-3096-11e6-90cc-2912389d2328.png)

![image](https://cloud.githubusercontent.com/assets/12179089/15989584/593c8d40-3098-11e6-8109-c03792d2600e.png)
Now I am unable to do anything in the application. When I clicked on logout, this is what I see:
![image](https://cloud.githubusercontent.com/assets/12179089/15989586/6b0ed640-3098-11e6-90f0-2996545e8ae3.png)

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close it.
