### ISSUE TITLE
Customer subscribed to both men and women lists on Mailchimp

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#88]
Hi Cyrus

The customer with an email id misra.swati19@gmail.com was subscribed to both Club M and Club F lists. 

I manually unsubscribed the customer from Club M.

**Comment by cyrus-gc** [comment]
Here we don’t  restrict end user  to download only a particular gender guide. Since the  user might create profile for both the genders and download them. Do you want to auto unsubscribe from the male list if the same user downloads a women's guide?

**Comment by mailanand75** [comment]
Actually, once they subscribe to Men's guide, don't enroll them in the women's guide list and vice versa.

**Comment by cyrus-gc** [comment]
Fixed. Please check in staging.
Please  clear cookies and use this "mailanand75@yahoo.com" mail Id. 
Note: We have removed this Id in database.
