### ISSUE TITLE
Blog formatting fixes

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#89]
Please review the blog post on staging titled "Sample".
1. The quoted text shows a vertical line on the left side. The length of the vertical line can be reduced in both the top and the bottom overhang in such a way that the extension of the line is only equivalent to one line space above and one line space below the quoted text.
2. Indent the entire quote text once so they are not left aligned with the rest of the paragraphs.
3. Use Italic and bold for the quoted text.
4. When we use numbered list, there is more than one line break on the top. This has to be corrected.
5. Font used should be the same as we have in our current production server.

**Comment by cyrus-gc** [comment]
Fixed in earlier versions. Please verify and close it.
