### ISSUE TITLE
Error messages for images above 1 MB

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#90]
When the user selects multiple images for any section and more that one image among the selected images is over 1 MB, the error message shown is "Whoa! One of the photographs is more than 1MB in size...." This error message should be used only the user uploads one image that is over 1 MB in size along with other images that is less than 1 MB in size.

This error message is wrong as more than one images are over 1MB in size. The correct error message should be "Whoa! Some of the photographs are more than...."

**Comment by cyrus-gc** [comment]
Fixed and Please test this in Staging.

Additionally, When all the user uploaded  images are greater than 1MB, we have implemented this error message as "Whoa! all the photographs are more than....".

**Comment by cyrus-gc** [comment]
Moved to Live. Please verify and close it.
