### ISSUE TITLE
Share Profile and Invite friends Button Highlight

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#92]
When the user opens the Share Profile tray, or Invite Friends Tray, it should remain highlighted while the user is working on the tray (such as entering the fields in the tray or any other action). The highlight should disappear when the user clicks on the button. This issue is shown as fixed in the Excel sheet but it is still not fixed,

**Comment by cyrus-gc** [comment]
Fixed. Please verify and close this issue.
