### ISSUE TITLE
Email formatting issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#96]
Here is a screenshot of the Jodi Logik email from a Desktop

![image](https://cloud.githubusercontent.com/assets/12179089/16754945/6bf4267a-4815-11e6-992d-2cb5aeef05fd.png)

**Comment by cyrus-gc** [comment]
we have handled this only for browser related mail servers like GMAIL,YAHOO, and not for other mail services at desktop.
