### ISSUE TITLE
Family & Beliefs Issue

### ISSUE THREAD

**Issue by mailanand75** [JodiLogik/phase_one#97]
I checked the family and beliefs section from another Desktop and faced the same formatting issue I reported earlier.

If clearing the cache is the only solution, it is not feasible to ask all customer to clear the cache every time we make an update to the product. The application has to handle this without clearing the cache.

Please read about this issue online and find out how other online applications don't seem to face this issue. I have never received any instruction from Facebook / LinkedIn / Twitter etc to clear my cache.

![image](https://cloud.githubusercontent.com/assets/12179089/16755039/1f2fed0a-4816-11e6-9372-f9733964c1e6.png)

**Comment by cyrus-gc** [comment]
This was occurred due to the grammarly browser extension in the old version. At Live Server it is not behaving as mentioned above. This is not an issue.
